### ISSUE TITLE
Suggestion: Embedded color media queries (high contrast, grey scale) 

### ISSUE THREAD

**Issue by notlee** [Financial-Times/logo-images#29]
Suggestion to improve logos in ms high contrast. (thanks @sjparkinson) 

It might also be possible/desirable to embed other color media queries https://drafts.csswg.org/mediaqueries-4/#color

```
/* Slightly enhance important images */
@media screen and (-ms-high-contrast: active) {
  img.hero {
    filter: brightness(1) contrast(1) saturate(1.5);
  }
}
```
https://rawgit.com/ericwbailey/working-with-high-contrast-mode-talk/master/index.html#/66

**Comment by JakeChampion** [comment]
A good issue on high contrast mode https://github.com/mozdevs/cssremedy/issues/62

**Comment by fuzzbomb** [comment]
The presence of the `.hero` class (or any other name) is something that can't be assumed. I don't think class selectors belong in reset/normalize/remedy stylesheets generally.
